### ISSUE TITLE
Move away from `dev` default

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-server#4]
The default server name is `bedrock.dev` https://github.com/digitalbazaar/bedrock-server/blob/master/lib/config.js#L15

`dev` is now a real TLD owned by google: https://www.iana.org/domains/root/db/dev.html

In certain circumstances, browsers will show a name collision error.

The thing to do seems to be to move to `bedrock.local`.

**Comment by dlongley** [comment]
Fine with `.local`, everyone else?
